scanner:
  paths:
    - "~/Projects"
    - "~/Scripts"
    - "~/Documents/Code"
  exclude:
    - "__pycache__"
    - ".git"
    - "node_modules"
    - "venv"
    - ".venv"
    - "build"
    - "dist"
    - "site-packages"
    - "lib/python"
    - "egg-info"
    - "wheels"
    - "deps"
    - "vendor"
    - "cache"
    - ".idea"
    - ".vscode"
    - "migrations"
    - "test_data"
    - "tmp"
    - "temp"
  max_file_size: 1048576  # 1MB
  extensions:
    python: [".py", ".pyw"]
    javascript: [".js", ".jsx", ".mjs"]
    typescript: [".ts", ".tsx"]
    shell: [".sh", ".bash", ".zsh"]
    config: ["Dockerfile", "Makefile", "package.json", "pyproject.toml"]
    html: [".html", ".htm"]
    css: [".css", ".scss", ".sass"]
    data: [".json", ".yaml", ".yml"]
    docs: [".md", ".rst"]
    other: [".java", ".c", ".cpp", ".h", ".go", ".rb", ".php"]